"""initial schema

Revision ID: 09d22d08e8d0
Revises: 
Create Date: 2026-07-17 14:16:35.142659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09d22d08e8d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('source_base_url', sa.String(length=500), nullable=False),
    sa.Column('source_slug', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'IN_PROGRESS', 'BREAK_PENDING', 'ELIMINATIONS', 'COMPLETED', name='tournamentstatus'), nullable=False),
    sa.Column('api_available', sa.Boolean(), nullable=False),
    sa.Column('api_last_checked_at', sa.String(length=50), nullable=True),
    sa.Column('champion_team_id', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['champion_team_id'], ['teams.id'], name='fk_tournaments_champion_team', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournaments')),
    sa.UniqueConstraint('slug', name=op.f('uq_tournaments_slug')),
    sa.UniqueConstraint('source_base_url', 'source_slug', name='uq_tournaments_source')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('break_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_general', sa.Boolean(), nullable=False),
    sa.Column('break_size', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_break_categories_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_break_categories')),
    sa.UniqueConstraint('tournament_id', 'slug', name='uq_break_categories_tournament_slug')
    )
    op.create_index(op.f('ix_break_categories_tournament_id'), 'break_categories', ['tournament_id'], unique=False)
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_institutions_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutions')),
    sa.UniqueConstraint('tournament_id', 'code', name='uq_institutions_tournament_code')
    )
    op.create_index(op.f('ix_institutions_tournament_id'), 'institutions', ['tournament_id'], unique=False)
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_leaderboard_entries_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leaderboard_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaderboard_entries')),
    sa.UniqueConstraint('tournament_id', 'user_id', name='uq_leaderboard_tournament_user')
    )
    op.create_index(op.f('ix_leaderboard_entries_tournament_id'), 'leaderboard_entries', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_user_id'), 'leaderboard_entries', ['user_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_rooms_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('tournament_id', 'name', name='uq_rooms_tournament_name')
    )
    op.create_index(op.f('ix_rooms_tournament_id'), 'rooms', ['tournament_id'], unique=False)
    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='scrapestatus'), nullable=False),
    sa.Column('strategy_used', sa.Enum('API', 'HTML_VUEDATA', 'HTML_LIST', name='scrapestrategy'), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('entities_created', sa.Integer(), nullable=False),
    sa.Column('entities_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_scrape_logs_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_logs'))
    )
    op.create_index(op.f('ix_scrape_logs_tournament_id'), 'scrape_logs', ['tournament_id'], unique=False)
    op.create_table('speaker_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_speaker_categories_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaker_categories')),
    sa.UniqueConstraint('tournament_id', 'slug', name='uq_speaker_categories_tournament_slug')
    )
    op.create_index(op.f('ix_speaker_categories_tournament_id'), 'speaker_categories', ['tournament_id'], unique=False)
    op.create_table('adjudicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('is_independent', sa.Boolean(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_adjudicators_institution_id_institutions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_adjudicators_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjudicators')),
    sa.UniqueConstraint('tournament_id', 'external_id', name='uq_adjudicators_tournament_external')
    )
    op.create_index(op.f('ix_adjudicators_external_id'), 'adjudicators', ['external_id'], unique=False)
    op.create_index(op.f('ix_adjudicators_tournament_id'), 'adjudicators', ['tournament_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.Enum('PRELIMINARY', 'ELIMINATION', name='roundstage'), nullable=False),
    sa.Column('break_category_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RELEASED', 'COMPLETED', name='roundstatus'), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['break_category_id'], ['break_categories.id'], name=op.f('fk_rounds_break_category_id_break_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_rounds_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rounds')),
    sa.UniqueConstraint('tournament_id', 'seq', name='uq_rounds_tournament_seq')
    )
    op.create_index(op.f('ix_rounds_tournament_id'), 'rounds', ['tournament_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_teams_institution_id_institutions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_teams_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('tournament_id', 'external_id', name='uq_teams_tournament_external')
    )
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=False)
    op.create_index(op.f('ix_teams_tournament_id'), 'teams', ['tournament_id'], unique=False)
    op.create_table('adjudicator_breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adjudicator_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.String(length=50), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adjudicator_id'], ['adjudicators.id'], name=op.f('fk_adjudicator_breaks_adjudicator_id_adjudicators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_adjudicator_breaks_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjudicator_breaks')),
    sa.UniqueConstraint('tournament_id', 'adjudicator_id', name='uq_adjudicator_breaks_tournament_adjudicator')
    )
    op.create_index(op.f('ix_adjudicator_breaks_adjudicator_id'), 'adjudicator_breaks', ['adjudicator_id'], unique=False)
    op.create_index(op.f('ix_adjudicator_breaks_tournament_id'), 'adjudicator_breaks', ['tournament_id'], unique=False)
    op.create_table('bet_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_type', sa.Enum('CHAMPION', 'TOP_N_BREAK', 'TOP_N_SPEAKERS', 'ROUND_WINNER', 'HEAD_TO_HEAD', 'BREAKOUT_TEAM', 'BEST_INSTITUTION', name='bettype'), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_round_id', sa.Integer(), nullable=True),
    sa.Column('target_break_category_id', sa.Integer(), nullable=True),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('points_rule', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'SETTLED', name='betmarketstatus'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_break_category_id'], ['break_categories.id'], name=op.f('fk_bet_markets_target_break_category_id_break_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_round_id'], ['rounds.id'], name=op.f('fk_bet_markets_target_round_id_rounds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_bet_markets_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bet_markets'))
    )
    op.create_index(op.f('ix_bet_markets_tournament_id'), 'bet_markets', ['tournament_id'], unique=False)
    op.create_table('break_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('break_category_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('as_of_round_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('projected_rank', sa.Integer(), nullable=True),
    sa.Column('points_needed', sa.JSON(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['as_of_round_id'], ['rounds.id'], name=op.f('fk_break_predictions_as_of_round_id_rounds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['break_category_id'], ['break_categories.id'], name=op.f('fk_break_predictions_break_category_id_break_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_break_predictions_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_break_predictions_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_break_predictions')),
    sa.UniqueConstraint('tournament_id', 'break_category_id', 'team_id', 'as_of_round_id', name='uq_break_predictions_category_team_round')
    )
    op.create_index(op.f('ix_break_predictions_as_of_round_id'), 'break_predictions', ['as_of_round_id'], unique=False)
    op.create_index(op.f('ix_break_predictions_break_category_id'), 'break_predictions', ['break_category_id'], unique=False)
    op.create_index(op.f('ix_break_predictions_team_id'), 'break_predictions', ['team_id'], unique=False)
    op.create_index(op.f('ix_break_predictions_tournament_id'), 'break_predictions', ['tournament_id'], unique=False)
    op.create_table('breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('break_category_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROJECTED', 'CONFIRMED', name='breakstatus'), nullable=False),
    sa.Column('confirmed_at', sa.String(length=50), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['break_category_id'], ['break_categories.id'], name=op.f('fk_breaks_break_category_id_break_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_breaks_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_breaks_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_breaks')),
    sa.UniqueConstraint('tournament_id', 'break_category_id', 'team_id', name='uq_breaks_category_team')
    )
    op.create_index(op.f('ix_breaks_break_category_id'), 'breaks', ['break_category_id'], unique=False)
    op.create_index(op.f('ix_breaks_team_id'), 'breaks', ['team_id'], unique=False)
    op.create_index(op.f('ix_breaks_tournament_id'), 'breaks', ['tournament_id'], unique=False)
    op.create_table('change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('CREATED', 'UPDATED', name='changetype'), nullable=False),
    sa.Column('field_diff', sa.JSON(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_change_events_round_id_rounds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_change_events_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_events'))
    )
    op.create_index(op.f('ix_change_events_entity_type'), 'change_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_change_events_tournament_id'), 'change_events', ['tournament_id'], unique=False)
    op.create_table('debates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', name='debatestatus'), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_debates_room_id_rooms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_debates_round_id_rounds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_debates_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debates')),
    sa.UniqueConstraint('tournament_id', 'external_id', name='uq_debates_tournament_external')
    )
    op.create_index(op.f('ix_debates_external_id'), 'debates', ['external_id'], unique=False)
    op.create_index(op.f('ix_debates_round_id'), 'debates', ['round_id'], unique=False)
    op.create_index(op.f('ix_debates_tournament_id'), 'debates', ['tournament_id'], unique=False)
    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_speakers_team_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_speakers_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speakers')),
    sa.UniqueConstraint('tournament_id', 'team_id', 'name', name='uq_speakers_tournament_team_name')
    )
    op.create_index(op.f('ix_speakers_external_id'), 'speakers', ['external_id'], unique=False)
    op.create_index(op.f('ix_speakers_team_id'), 'speakers', ['team_id'], unique=False)
    op.create_index(op.f('ix_speakers_tournament_id'), 'speakers', ['tournament_id'], unique=False)
    op.create_table('team_break_categories',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('break_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['break_category_id'], ['break_categories.id'], name=op.f('fk_team_break_categories_break_category_id_break_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_break_categories_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'break_category_id', name=op.f('pk_team_break_categories'))
    )
    op.create_table('debate_adjudicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debate_id', sa.Integer(), nullable=False),
    sa.Column('adjudicator_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('CHAIR', 'PANELLIST', 'TRAINEE', name='judgerole'), nullable=False),
    sa.ForeignKeyConstraint(['adjudicator_id'], ['adjudicators.id'], name=op.f('fk_debate_adjudicators_adjudicator_id_adjudicators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], name=op.f('fk_debate_adjudicators_debate_id_debates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debate_adjudicators')),
    sa.UniqueConstraint('debate_id', 'adjudicator_id', name='uq_debate_adjudicators_debate_adjudicator')
    )
    op.create_index(op.f('ix_debate_adjudicators_adjudicator_id'), 'debate_adjudicators', ['adjudicator_id'], unique=False)
    op.create_index(op.f('ix_debate_adjudicators_debate_id'), 'debate_adjudicators', ['debate_id'], unique=False)
    op.create_table('debate_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debate_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Enum('OPENING_GOVERNMENT', 'OPENING_OPPOSITION', 'CLOSING_GOVERNMENT', 'CLOSING_OPPOSITION', name='bpposition'), nullable=False),
    sa.Column('rank_in_debate', sa.Integer(), nullable=True),
    sa.Column('team_points', sa.Integer(), nullable=True),
    sa.Column('speaker_points_total', sa.Float(), nullable=True),
    sa.Column('advanced', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], name=op.f('fk_debate_teams_debate_id_debates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_debate_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debate_teams')),
    sa.UniqueConstraint('debate_id', 'position', name='uq_debate_teams_debate_position'),
    sa.UniqueConstraint('debate_id', 'team_id', name='uq_debate_teams_debate_team')
    )
    op.create_index(op.f('ix_debate_teams_debate_id'), 'debate_teams', ['debate_id'], unique=False)
    op.create_index(op.f('ix_debate_teams_team_id'), 'debate_teams', ['team_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_market_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'LOCKED', 'SETTLED', name='predictionstatus'), nullable=False),
    sa.Column('points_awarded', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bet_market_id'], ['bet_markets.id'], name=op.f('fk_predictions_bet_market_id_bet_markets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_predictions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions')),
    sa.UniqueConstraint('bet_market_id', 'user_id', name='uq_predictions_market_user')
    )
    op.create_index(op.f('ix_predictions_bet_market_id'), 'predictions', ['bet_market_id'], unique=False)
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debate_id', sa.Integer(), nullable=False),
    sa.Column('ballot_source_url', sa.String(length=500), nullable=True),
    sa.Column('motion_text', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], name=op.f('fk_results_debate_id_debates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results')),
    sa.UniqueConstraint('debate_id', name=op.f('uq_results_debate_id'))
    )
    op.create_table('speaker_category_links',
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('speaker_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['speaker_category_id'], ['speaker_categories.id'], name=op.f('fk_speaker_category_links_speaker_category_id_speaker_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_speaker_category_links_speaker_id_speakers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('speaker_id', 'speaker_category_id', name=op.f('pk_speaker_category_links'))
    )
    op.create_table('speaker_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debate_team_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('PM', 'DPM', 'LO', 'DLO', 'MG', 'GW', 'MO', 'OW', name='speakerrole'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_iron', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['debate_team_id'], ['debate_teams.id'], name=op.f('fk_speaker_scores_debate_team_id_debate_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_speaker_scores_speaker_id_speakers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaker_scores')),
    sa.UniqueConstraint('debate_team_id', 'role', name='uq_speaker_scores_debate_team_role')
    )
    op.create_index(op.f('ix_speaker_scores_debate_team_id'), 'speaker_scores', ['debate_team_id'], unique=False)
    op.create_index(op.f('ix_speaker_scores_speaker_id'), 'speaker_scores', ['speaker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speaker_scores_speaker_id'), table_name='speaker_scores')
    op.drop_index(op.f('ix_speaker_scores_debate_team_id'), table_name='speaker_scores')
    op.drop_table('speaker_scores')
    op.drop_table('speaker_category_links')
    op.drop_table('results')
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_bet_market_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_debate_teams_team_id'), table_name='debate_teams')
    op.drop_index(op.f('ix_debate_teams_debate_id'), table_name='debate_teams')
    op.drop_table('debate_teams')
    op.drop_index(op.f('ix_debate_adjudicators_debate_id'), table_name='debate_adjudicators')
    op.drop_index(op.f('ix_debate_adjudicators_adjudicator_id'), table_name='debate_adjudicators')
    op.drop_table('debate_adjudicators')
    op.drop_table('team_break_categories')
    op.drop_index(op.f('ix_speakers_tournament_id'), table_name='speakers')
    op.drop_index(op.f('ix_speakers_team_id'), table_name='speakers')
    op.drop_index(op.f('ix_speakers_external_id'), table_name='speakers')
    op.drop_table('speakers')
    op.drop_index(op.f('ix_debates_tournament_id'), table_name='debates')
    op.drop_index(op.f('ix_debates_round_id'), table_name='debates')
    op.drop_index(op.f('ix_debates_external_id'), table_name='debates')
    op.drop_table('debates')
    op.drop_index(op.f('ix_change_events_tournament_id'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_entity_type'), table_name='change_events')
    op.drop_table('change_events')
    op.drop_index(op.f('ix_breaks_tournament_id'), table_name='breaks')
    op.drop_index(op.f('ix_breaks_team_id'), table_name='breaks')
    op.drop_index(op.f('ix_breaks_break_category_id'), table_name='breaks')
    op.drop_table('breaks')
    op.drop_index(op.f('ix_break_predictions_tournament_id'), table_name='break_predictions')
    op.drop_index(op.f('ix_break_predictions_team_id'), table_name='break_predictions')
    op.drop_index(op.f('ix_break_predictions_break_category_id'), table_name='break_predictions')
    op.drop_index(op.f('ix_break_predictions_as_of_round_id'), table_name='break_predictions')
    op.drop_table('break_predictions')
    op.drop_index(op.f('ix_bet_markets_tournament_id'), table_name='bet_markets')
    op.drop_table('bet_markets')
    op.drop_index(op.f('ix_adjudicator_breaks_tournament_id'), table_name='adjudicator_breaks')
    op.drop_index(op.f('ix_adjudicator_breaks_adjudicator_id'), table_name='adjudicator_breaks')
    op.drop_table('adjudicator_breaks')
    op.drop_index(op.f('ix_teams_tournament_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_rounds_tournament_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_adjudicators_tournament_id'), table_name='adjudicators')
    op.drop_index(op.f('ix_adjudicators_external_id'), table_name='adjudicators')
    op.drop_table('adjudicators')
    op.drop_index(op.f('ix_speaker_categories_tournament_id'), table_name='speaker_categories')
    op.drop_table('speaker_categories')
    op.drop_index(op.f('ix_scrape_logs_tournament_id'), table_name='scrape_logs')
    op.drop_table('scrape_logs')
    op.drop_index(op.f('ix_rooms_tournament_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_leaderboard_entries_user_id'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_tournament_id'), table_name='leaderboard_entries')
    op.drop_table('leaderboard_entries')
    op.drop_index(op.f('ix_institutions_tournament_id'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_break_categories_tournament_id'), table_name='break_categories')
    op.drop_table('break_categories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
